INSERT into studenti (nome, cognome, email) values
("RICCARDO","GABOSSI","riccardo.gabossi@edu.itspiemonte.it"),
("VLADIMIR","VIBIO","vladimir.vibio@edu.itspiemonte.it"),
("GIORGIO","MASERAZZO","giorgio.maserazzo@edu.itspiemonte.it"),
("STEFANO","SCICOLONE","stefano.scicolone@edu.itspiemonte.it"),
("DAVIDE","COLANGELO","davide.colangelo@edu.itspiemonte.it"),
("FABRIZIO","DE CICCO", "fabrizio.decicco@edu.itspiemonte.it"),
("SIMONE","RORATO","simone.rorato@edu.itspiemonte.it"),
("LORENZO","SCARPA","lorenzo.scarpa@edu.itspiemonte.it"),
("SIMONE","FUOCO","simone.fuoco@edu.itspiemonte.it"),
("ALESSANDRO","VIOTTI","alessandro.viotti@edu.itspiemonte.it"),
("ROSA","BUONO","rosa.buono@edu.itspiemonte.it"),
("STEFA),","ADAMO","stefano.adamo@edu.itspiemonte.it"),
("TONY","FAVA","tony.fava@edu.itspiemonte.it"),
("FRANCES),","TALOMO","francesco.talomo@edu.itspiemonte.it"),
("LUIGI","BOTTASSO","luigi.bottasso@edu.itspiemonte.it"),
("MARCO","DE GENNARO", "marco.degennaro@edu.itspiemonte.it"),
("EMANUELE","GALLINA","alessandro.gallina@edu.itspiemonte.it"),
("MARCO","ANTONINO","marco.antonino@edu.itspiemonte.it"),
("ANDREA","SCAVUZZO","andrea.scavuzzo@edu.itspiemonte.it"),
("THOMAS","OWENS","thomas.owens@edu.itspiemonte.it"),
("ALESSANDRO","FLERES","alessandro.fleres@edu.itspiemonte.it"),
("DANILO","CAPPELLINO","danilo.cappellino@edu.itspiemonte.it"),
("VINCENZO","DI DOMENICO", "vincenzo.didomenico@edu.itspiemonte.it"),
("EDOARDO","ELIA","edoardo.elia@edu.itspiemonte.it"),
("SIMONE","VOLPE","simone.volpe@edu.itspiemonte.it"),
("MATTIA","VICENZI","mattia.vicenzi@edu.itspiemonte.it"),
("MARCO","PANZANARO","marco.panzanaro@edu.itspiemonte.it");
